# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa38a19dc971f0c1bdd3967409aee4860aa40495929693385f7a8b8a572ec541dc66dbd537f2afeb84d6cd4ecc8282eae0934de1f9322ac191a6623decb250b

test:
  secret_key_base: ae17218e24e6163d141e8a35d7841a553d2f50596af43255f57db7a946a425c48bf1d7b952b15f5bd7c83f52ef03eca24d34968e469d40bff5573df1469cb23b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
